inherit_from: .rubocop_todo.yml

require:
  - rubocop-factory_bot
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-rspec_rails
  - rubocop-git

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  TargetRailsVersion: 7.2
  Exclude:
    - bin/**/*
    - config/environments/*
    - db/schema.rb
    - log/**/*
    - node_modules/**/*
    - test/fixtures/**/*
    - tmp/**/*
    - vendor/**/*
    - vendor/bundle/**/*
    - config/initializers/*
    - db/seeds.rb

#  Metrics cops
Metrics/ClassLength:
  CountComments: false
  Max: 400
  Enabled: true

Metrics/ModuleLength:
  CountComments: false
  Max: 400
  Enabled: true

Metrics/ParameterLists:
  Max: 6
  CountKeywordArgs: true
  Enabled: true

Metrics/MethodLength:
  CountComments: false
  Max: 40
  Enabled: true

Metrics/BlockLength:
  CountComments: false
  Max: 25
  Enabled: true
  Exclude:
    - config/**/*
    - db/data/*
    - db/migrate/*
    - spec/**/*

Metrics/BlockNesting:
  Max: 4
  Enabled: true

Metrics/CyclomaticComplexity:
  Max: 15
  Enabled: true

Metrics/PerceivedComplexity:
  Max: 20
  Enabled: true

Metrics/AbcSize:
  Enabled: true
  Max: 30

# Layout cops
Layout/LineLength:
  Enabled: true
  Max: 120

# Style cops
Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

# RSpec cops - relaxed for spec files
RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15

RSpec/VerifiedDoubles:
  Enabled: false

RSpec/AnyInstance:
  Enabled: false
