inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-git

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.0
  TargetRailsVersion: 7.0
  Exclude:
    - 'bin/**/*'
    - 'config/environments/*'
    - 'db/schema.rb
    - 'log/**/*'
    - 'node_modules/**/*'
    - 'test/fixtures/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

#  Metrics cops
Metrics/ClassLength:
  CountComments: false
  Max: 200
  Enabled: true

Metrics/ModuleLength:
  CountComments: false
  Max: 200
  Enabled: true

Metrics/ParameterLists:
  Max: 6
  CountKeywordArgs: true
  Enabled: true

Metrics/MethodLength:
  CountComments: false
  Max: 20
  Enabled: true

Metrics/BlockLength:
  CountComments: false
  Max: 15
  Enabled: true
  Exclude:
    - 'config/**/*'
    - 'db/data/*'
    - 'db/migrate/*'
    - 'spec/**/*'

Metrics/BlockNesting:
  Max: 4
  Enabled: true

Metrics/CyclomaticComplexity:
  Max: 6
  Enabled: true

Metrics/PerceivedComplexity:
  Max: 12
  Enabled: true

Metrics/AbcSize:
  Enabled: true
  Max: 19

# Layout cops
Layout/LineLength:
  Enabled: true
  Max: 120

# Style cops
Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/LineEndConcatenation:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: single_quotes
  Enabled: true

Style/Documentation:
  Enabled: false
